{"name": "test_03_random", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6\n +  where 5 = randint(1, 10)", "trace": "self = <test_api.TestApi object at 0x000002852C006B30>\n\n    def test_03_random(self):\n>       assert randint(1, 10) == 6\nE       assert 5 == 6\nE        +  where 5 = randint(1, 10)\n\ncase\\test_api.py:70: AssertionError"}, "start": 1675931710364, "stop": 1675931710364, "uuid": "23a4999d-ce42-493a-98cc-8fc6724f3285", "historyId": "a1dcd68f510a121e7a5c7b75d58a34de", "testCaseId": "0b9b12c813b1e69b3ea65aed815da048", "fullName": "case.test_api.TestApi#test_03_random", "labels": [{"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "DESKTOP-RU8TPQH"}, {"name": "thread", "value": "32988-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_api"}]}